# Generated by Django 6.0.6 on 2026-06-26 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corraleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Corraleta',
                'verbose_name_plural': 'Corraletas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ParadaRecorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('corraleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ganado.corraleta')),
            ],
            options={
                'verbose_name': 'Parada de recorrido',
                'verbose_name_plural': 'Paradas de recorrido',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RecorridoGanado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_cabezas', models.IntegerField(blank=True, null=True)),
                ('estado_hato', models.CharField(choices=[('bien', 'Bien'), ('alerta', 'Alerta'), ('critico', 'Crítico')], max_length=10)),
                ('color', models.CharField(choices=[('azul_claro', 'Azul claro'), ('rojo', 'Rojo'), ('verde', 'Verde'), ('naranja', 'Naranja'), ('morado', 'Morado'), ('amarillo', 'Amarillo')], default='azul_claro', max_length=20)),
                ('narrativa', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asistentes', models.ManyToManyField(blank=True, related_name='recorridos_asistidos', to=settings.AUTH_USER_MODEL)),
                ('corraletas_visitadas', models.ManyToManyField(blank=True, through='ganado.ParadaRecorrido', to='ganado.corraleta')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorridos_creados', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorridos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recorrido de ganado',
                'verbose_name_plural': 'Recorridos de ganado',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paradarecorrido',
            name='recorrido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='ganado.recorridoganado'),
        ),
        migrations.CreateModel(
            name='FotoRecorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='ganado/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ganado.recorridoganado')),
            ],
            options={
                'verbose_name': 'Foto de recorrido',
                'verbose_name_plural': 'Fotos de recorrido',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='paradarecorrido',
            unique_together={('recorrido', 'orden')},
        ),
    ]
