# Generated by Django 6.0.6 on 2026-06-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0003_ganado_estado_parada_libre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradarecorrido',
            name='hora_llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recorridoganado',
            name='estado',
            field=models.CharField(choices=[('en_curso', 'En curso'), ('finalizado', 'Finalizado')], default='en_curso', max_length=15),
        ),
    ]
