# Generated by Django 6.0.6 on 2026-07-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0004_alter_paradarecorrido_hora_llegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corraleta',
            name='lat',
            field=models.DecimalField(decimal_places=12, max_digits=18),
        ),
        migrations.AlterField(
            model_name='corraleta',
            name='lng',
            field=models.DecimalField(decimal_places=12, max_digits=18),
        ),
        migrations.AlterField(
            model_name='paradarecorrido',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='paradarecorrido',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True),
        ),
    ]
