# Generated by Django 6.0.6 on 2026-07-05 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0005_alter_corraleta_lat_alter_corraleta_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorridoganado',
            name='plan_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorridos_reales', to='ganado.recorridoganado'),
        ),
        migrations.AddField(
            model_name='recorridoganado',
            name='tipo',
            field=models.CharField(choices=[('planeado', 'Planeado'), ('real', 'Real')], default='real', max_length=10),
        ),
    ]
