# Generated by Django 6.0.6 on 2026-08-11 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0006_recorridoganado_plan_referencia_recorridoganado_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('recorrido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignacion_spot', to='ganado.recorridoganado')),
            ],
            options={
                'verbose_name': 'Asignación SPOT',
                'verbose_name_plural': 'Asignaciones SPOT',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PosicionSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_message_id', models.IntegerField(unique=True)),
                ('lat', models.DecimalField(decimal_places=12, max_digits=18)),
                ('lng', models.DecimalField(decimal_places=12, max_digits=18)),
                ('altitud', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_spot', models.DateTimeField()),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('TRACK', 'Track'), ('STOP', 'Stop'), ('OK', 'Ok'), ('HELP', 'Help'), ('CUSTOM', 'Custom')], default='TRACK', max_length=20)),
                ('bateria', models.CharField(choices=[('GOOD', 'Buena'), ('LOW', 'Baja'), ('CRITICAL', 'Crítica')], default='GOOD', max_length=20)),
                ('dentro_perimetro', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='ganado.asignacionspot')),
            ],
            options={
                'verbose_name': 'Posición SPOT',
                'verbose_name_plural': 'Posiciones SPOT',
                'ordering': ['-fecha_hora_spot'],
            },
        ),
        migrations.CreateModel(
            name='AlertaSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sin_senal', 'Sin señal'), ('fuera_perimetro', 'Fuera del perímetro'), ('bateria_baja', 'Batería baja'), ('bateria_critica', 'Batería crítica')], max_length=20)),
                ('mensaje', models.TextField()),
                ('resuelta', models.BooleanField(default=False)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_spot_resueltas', to=settings.AUTH_USER_MODEL)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='ganado.asignacionspot')),
                ('posicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ganado.posicionspot')),
            ],
            options={
                'verbose_name': 'Alerta SPOT',
                'verbose_name_plural': 'Alertas SPOT',
                'ordering': ['-created_at'],
            },
        ),
    ]
