# Generated by Django 6.0.6 on 2026-08-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0007_asignacionspot_posicionspot_alertaspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionspot',
            name='nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
