# Generated by Django 6.0.6 on 2026-08-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0008_asignacionspot_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicionspot',
            name='spot_message_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
