# Generated by Django 6.0.6 on 2026-08-21 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0009_alter_posicionspot_spot_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaspot',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='ganado.asignacionspot'),
        ),
        migrations.AlterField(
            model_name='posicionspot',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posiciones', to='ganado.asignacionspot'),
        ),
    ]
