# Generated by Django 6.0.6 on 2026-09-01 03:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0010_movimientoinventario_solicitud_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.PositiveSmallIntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_avance', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avances_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avance de proyecto',
                'verbose_name_plural': 'Avances de proyecto',
                'ordering': ['-fecha_avance', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('especialidad', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('rfc', models.CharField(blank=True, max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratistas_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contratista',
                'verbose_name_plural': 'Contratistas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CompraProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_compra', models.CharField(blank=True, max_length=20, unique=True)),
                ('proveedor_nombre', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requiere_autorizacion', models.BooleanField(default=False)),
                ('autorizado_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente_autorizacion', 'Pendiente de autorización'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada'), ('en_proceso', 'En proceso'), ('completada', 'Completada')], default='pendiente_autorizacion', max_length=25)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_proyecto_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_proyecto_creadas', to=settings.AUTH_USER_MODEL)),
                ('contratista_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_proyecto', to='proyectos.contratista')),
            ],
            options={
                'verbose_name': 'Compra de proyecto',
                'verbose_name_plural': 'Compras de proyecto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FotoAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='proyectos/avances/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='proyectos.avanceproyecto')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos_avance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de avance',
                'verbose_name_plural': 'Fotos de avance',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FotoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='proyectos/compras/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='proyectos.compraproyecto')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fotos_compra_proyecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de compra',
                'verbose_name_plural': 'Fotos de compra',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proyecto', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad', models.CharField(max_length=30)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_proyecto', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Ítem de proyecto',
                'verbose_name_plural': 'Ítems de proyecto',
                'ordering': ['codigo_proyecto'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('devolucion', 'Devolución')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_resultante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_uso', models.TextField(blank=True)),
                ('fecha_movimiento', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compra_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='proyectos.compraproyecto')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='proyectos.itemproyecto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_proyecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de proyecto',
                'verbose_name_plural': 'Movimientos de proyecto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('autorizado', 'Autorizado'), ('en_progreso', 'En progreso'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', max_length=15)),
                ('presupuesto_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requiere_autorizacion', models.BooleanField(default=False)),
                ('autorizado_en', models.DateTimeField(blank=True, null=True)),
                ('notas_autorizacion', models.TextField(blank=True)),
                ('fecha_inicio_estimada', models.DateField(blank=True, null=True)),
                ('fecha_inicio_real', models.DateField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='itemproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proyectos.proyecto'),
        ),
        migrations.CreateModel(
            name='DevolucionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto_inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_proyecto', to='inventario.producto')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='proyectos.itemproyecto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Devolución a inventario',
                'verbose_name_plural': 'Devoluciones a inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionManoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_trabajo', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('aprobada_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('archivo_cotizacion', models.FileField(blank=True, null=True, upload_to='proyectos/cotizaciones/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='proyectos.contratista')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Cotización de mano de obra',
                'verbose_name_plural': 'Cotizaciones de mano de obra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='compraproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='proyectos.proyecto'),
        ),
        migrations.AddField(
            model_name='avanceproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='proyectos.proyecto'),
        ),
    ]
