from django.urls import path

from .views import (
    AlertasStockView,
    AutorizarSolicitudView,
    CategoriaInventarioListView,
    ComparativoSolicitudView,
    EnviarRelacionComprasView,
    EnviarSolicitudView,
    MovimientoDetailView,
    MovimientoListCreateView,
    ProductoDetailView,
    ProductoListCreateView,
    ProductoMovimientosView,
    RechazarSolicitudView,
    RecepcionesSolicitudView,
    RegistrarCompraView,
    RelacionComprasDetailView,
    RelacionComprasListCreateView,
    ReporteFaltanteListCreateView,
    ResolverReporteView,
    ResumenInventarioView,
    SolicitudDetailView,
    SolicitudListCreateView,
    UbicacionListView,
    ValidarMovimientoView,
)

urlpatterns = [
    path('productos/', ProductoListCreateView.as_view(), name='producto-list-create'),
    path('productos/<int:pk>/', ProductoDetailView.as_view(), name='producto-detail'),
    path('productos/<int:pk>/movimientos/', ProductoMovimientosView.as_view(), name='producto-movimientos'),
    path('movimientos/', MovimientoListCreateView.as_view(), name='movimiento-list-create'),
    path('movimientos/<int:pk>/', MovimientoDetailView.as_view(), name='movimiento-detail'),
    path('movimientos/<int:pk>/validar/', ValidarMovimientoView.as_view(), name='movimiento-validar'),
    path('categorias/', CategoriaInventarioListView.as_view(), name='categoria-list'),
    path('ubicaciones/', UbicacionListView.as_view(), name='ubicacion-list'),
    path('alertas-stock/', AlertasStockView.as_view(), name='alertas-stock'),
    path('resumen/', ResumenInventarioView.as_view(), name='inventario-resumen'),
    path('solicitudes/', SolicitudListCreateView.as_view(), name='solicitud-list-create'),
    path('solicitudes/<int:pk>/', SolicitudDetailView.as_view(), name='solicitud-detail'),
    path('solicitudes/<int:pk>/autorizar/', AutorizarSolicitudView.as_view(), name='solicitud-autorizar'),
    path('solicitudes/<int:pk>/rechazar/', RechazarSolicitudView.as_view(), name='solicitud-rechazar'),
    path('solicitudes/<int:pk>/enviar/', EnviarSolicitudView.as_view(), name='solicitud-enviar'),
    path('solicitudes/<int:pk>/recepciones/', RecepcionesSolicitudView.as_view(), name='solicitud-recepciones'),
    path('solicitudes/<int:pk>/comparativo/', ComparativoSolicitudView.as_view(), name='solicitud-comparativo'),
    path('solicitudes/<int:pk>/compra/', RegistrarCompraView.as_view(), name='solicitud-compra'),
    path('relaciones-compras/', RelacionComprasListCreateView.as_view(), name='relacion-compras-list-create'),
    path('relaciones-compras/<int:pk>/', RelacionComprasDetailView.as_view(), name='relacion-compras-detail'),
    path(
        'relaciones-compras/<int:pk>/enviar/', EnviarRelacionComprasView.as_view(), name='relacion-compras-enviar',
    ),
    path('reportes-faltantes/', ReporteFaltanteListCreateView.as_view(), name='reporte-faltante-list-create'),
    path('reportes-faltantes/<int:pk>/resolver/', ResolverReporteView.as_view(), name='reporte-faltante-resolver'),
]
