# Generated by Django 6.0.6 on 2026-07-09 03:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('camioneta', 'Camioneta'), ('camion', 'Camión'), ('moto', 'Moto'), ('cuatrimoto', 'Cuatrimoto'), ('utv', 'UTV'), ('otro', 'Otro')], max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('placas', models.CharField(blank=True, max_length=20)),
                ('numero_serie', models.CharField(blank=True, max_length=50)),
                ('kilometraje_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uso_asignacion', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_taller', 'En taller'), ('de_baja', 'De baja')], default='activo', max_length=15)),
                ('fecha_vencimiento_tenencia', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento_placas', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='flota/vehiculos/')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(choices=[('salida', 'Salida'), ('llegada', 'Llegada')], max_length=10)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('km_reporte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carroceria_pintura', models.BooleanField(default=False)),
                ('parabrisas_vidrios', models.BooleanField(default=False)),
                ('neumaticos_presion', models.BooleanField(default=False)),
                ('luces_delanteras_traseras', models.BooleanField(default=False)),
                ('interiores_asientos', models.BooleanField(default=False)),
                ('nivel_combustible', models.IntegerField()),
                ('nivel_aceite', models.BooleanField(default=False)),
                ('nivel_refrigerante', models.BooleanField(default=False)),
                ('nivel_liquido_frenos', models.BooleanField(default=False)),
                ('frenos_respuesta', models.BooleanField(default=False)),
                ('direccion_volante', models.BooleanField(default=False)),
                ('suspension_amortiguadores', models.BooleanField(default=False)),
                ('filtro_aire', models.BooleanField(default=False)),
                ('gato', models.BooleanField(default=False)),
                ('cruzeta', models.BooleanField(default=False)),
                ('llanta_refaccion', models.BooleanField(default=False)),
                ('caja_herramientas', models.BooleanField(default=False)),
                ('cables_corriente', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('validado', models.BooleanField(default=False)),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists_flota', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_validados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Checklist de vehículo',
                'verbose_name_plural': 'Checklists de vehículos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='FotoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='flota/checklists/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='flota.checklistvehiculo')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de checklist',
                'verbose_name_plural': 'Fotos de checklist',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertaFlota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cambio_aceite', 'Cambio de aceite'), ('calibracion_llantas', 'Calibración de llantas'), ('vencimiento_tenencia', 'Vencimiento de tenencia'), ('vencimiento_placas', 'Vencimiento de placas'), ('mantenimiento_general', 'Mantenimiento general')], max_length=25)),
                ('descripcion', models.TextField()),
                ('km_alerta', models.IntegerField(blank=True, null=True)),
                ('fecha_alerta', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_flota_resueltas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Alerta de flota',
                'verbose_name_plural': 'Alertas de flota',
                'ordering': ['-created_at'],
            },
        ),
    ]
