# Generated by Django 6.0.6 on 2026-07-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_precarga_vehiculos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='equipo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('camioneta', 'Camioneta'), ('camion', 'Camión'), ('moto', 'Moto'), ('cuatrimoto', 'Cuatrimoto'), ('utv', 'UTV'), ('polaris', 'Polaris'), ('can_am', 'CAN AM'), ('remolque', 'Remolque'), ('traila', 'Traila'), ('maquinaria', 'Maquinaria'), ('plataforma', 'Plataforma'), ('van', 'Van'), ('otro', 'Otro')], max_length=20),
        ),
    ]
