from django.db import migrations

PLACEHOLDERS = ['Savana', 'Blazer', 'Polaris', 'Cuatrimoto Roja', 'Moto Azul', 'Camión']

VEHICULOS_REALES = [
    {
        'equipo': 'CAN AM Outlander',
        'nombre': 'Moto roja',
        'tipo': 'cuatrimoto',
        'marca': 'CAN AM',
        'modelo': 'Outlander',
        'anio': 2022,
        'color': 'Roja',
        'uso_asignacion': 'Recorrido en campo',
        'kilometraje_actual': 0,
        'placas': '',
        'numero_serie': '3JBLGAR49NJ003153',
        'estado': 'activo',
    },
    {
        'equipo': 'Polaris Sport Man',
        'nombre': 'Moto azul',
        'tipo': 'cuatrimoto',
        'marca': 'Polaris',
        'modelo': 'Sport Man',
        'anio': 2022,
        'color': 'Azul',
        'uso_asignacion': 'Recorrido en campo',
        'kilometraje_actual': 0,
        'placas': '',
        'numero_serie': '4XASDA574NB196181',
        'estado': 'activo',
    },
    {
        'equipo': 'Caterpillar',
        'nombre': 'El piolin',
        'tipo': 'maquinaria',
        'marca': 'Caterpillar',
        'modelo': 'Pendiente',
        'anio': None,
        'color': 'Amarillo',
        'uso_asignacion': 'Carga pesada',
        'kilometraje_actual': 0,
        'placas': '',
        'numero_serie': 'INF PENDIENTE',
        'estado': 'activo',
    },
    {
        'equipo': 'Polaris Ranger 1000',
        'nombre': 'El 1000',
        'tipo': 'polaris',
        'marca': 'Polaris',
        'modelo': 'Ranger 1000',
        'anio': 2021,
        'color': 'Azul',
        'uso_asignacion': 'Trabajo en campo',
        'kilometraje_actual': 18488.5,
        'placas': '',
        'numero_serie': '4XAT6E997M8406303',
        'estado': 'activo',
    },
    {
        'equipo': 'Remolque 1',
        'nombre': 'Traila 1',
        'tipo': 'traila',
        'marca': 'Fabricada',
        'modelo': '4x5',
        'anio': None,
        'color': '',
        'uso_asignacion': 'Carga y traslado de material',
        'kilometraje_actual': 0,
        'placas': '',
        'numero_serie': '',
        'estado': 'activo',
    },
    {
        'equipo': 'Remolque 2',
        'nombre': 'Traila 2',
        'tipo': 'traila',
        'marca': 'Fabricada',
        'modelo': '4x5',
        'anio': None,
        'color': '',
        'uso_asignacion': 'Carga y traslado de material',
        'kilometraje_actual': 0,
        'placas': '',
        'numero_serie': '',
        'estado': 'activo',
    },
    {
        'equipo': 'Remolque 3',
        'nombre': 'Traila 3',
        'tipo': 'traila',
        'marca': 'Fabricada',
        'modelo': '4x5',
        'anio': None,
        'color': '',
        'uso_asignacion': 'Carga y traslado de material',
        'kilometraje_actual': 0,
        'placas': '',
        'numero_serie': '',
        'estado': 'activo',
    },
    {
        'equipo': 'Remolque 4',
        'nombre': 'Traila 4',
        'tipo': 'traila',
        'marca': 'Fabricada',
        'modelo': '4x5',
        'anio': None,
        'color': '',
        'uso_asignacion': 'Carga y traslado de material',
        'kilometraje_actual': 0,
        'placas': '',
        'numero_serie': '',
        'estado': 'activo',
    },
    {
        'equipo': 'CAN AM 8ZSB #1',
        'nombre': '166/#1 amarillo',
        'tipo': 'can_am',
        'marca': 'CAN AM',
        'modelo': '8ZSB',
        'anio': 2025,
        'color': 'Verde',
        'uso_asignacion': 'Recorrido en campo',
        'kilometraje_actual': 278.5,
        'placas': '',
        'numero_serie': '3JBUBAJ48SK000166',
        'estado': 'activo',
    },
    {
        'equipo': 'CAN AM 8ZSB #2',
        'nombre': '107/#2 cafe',
        'tipo': 'can_am',
        'marca': 'CAN AM',
        'modelo': '8ZSB',
        'anio': 2025,
        'color': 'Verde',
        'uso_asignacion': 'Recorrido en campo',
        'kilometraje_actual': 1938.0,
        'placas': '',
        'numero_serie': '3JBUBAJ43SK000107',
        'estado': 'activo',
    },
    {
        'equipo': 'Chevrolet Sierra',
        'nombre': 'sierra',
        'tipo': 'camioneta',
        'marca': 'Chevrolet',
        'modelo': 'Sierra',
        'anio': 2023,
        'color': 'Blanca',
        'uso_asignacion': 'Trabajo en campo',
        'kilometraje_actual': 313371.6,
        'placas': 'EN0569D',
        'numero_serie': '3GTP29E22DG159790',
        'estado': 'activo',
    },
    {
        'equipo': 'Chevrolet Blazer',
        'nombre': 'blazer',
        'tipo': 'camioneta',
        'marca': 'Chevrolet',
        'modelo': 'Blazer',
        'anio': 1989,
        'color': '',
        'uso_asignacion': 'Trabajo en campo',
        'kilometraje_actual': 0.0,
        'placas': 'A41RAG2',
        'numero_serie': '1GNEV18K4KF113735',
        'estado': 'activo',
    },
    {
        'equipo': 'Toyota Tacoma',
        'nombre': 'toyota',
        'tipo': 'camioneta',
        'marca': 'Toyota',
        'modelo': 'Tacoma TRD Sport Doble Cabina 24V',
        'anio': 2015,
        'color': 'Roja',
        'uso_asignacion': 'Uso personal ALB',
        'kilometraje_actual': 118657,
        'placas': 'EN0568D',
        'numero_serie': '3TMLU4EN6FM192821',
        'estado': 'activo',
    },
    {
        'equipo': 'Remolque Hechizos',
        'nombre': 'remolque',
        'tipo': 'remolque',
        'marca': 'Hechizo',
        'modelo': 'Remolque',
        'anio': 2009,
        'color': '',
        'uso_asignacion': 'Uso ganadero',
        'kilometraje_actual': 0,
        'placas': '6CY243A',
        'numero_serie': 'RE0902000186',
        'estado': 'activo',
    },
    {
        'equipo': 'Polaris Ranger 700',
        'nombre': 'El 700',
        'tipo': 'polaris',
        'marca': 'Polaris',
        'modelo': 'Ranger 700',
        'anio': 2009,
        'color': 'Verde',
        'uso_asignacion': 'Trabajo en campo',
        'kilometraje_actual': 0,
        'placas': '',
        'numero_serie': '4XAWH68A792714185',
        'estado': 'de_baja',
    },
    {
        'equipo': 'Plataforma Ganadera',
        'nombre': 'plataforma',
        'tipo': 'plataforma',
        'marca': 'N/A',
        'modelo': 'Plataforma Ganadera',
        'anio': None,
        'color': '',
        'uso_asignacion': 'Carga y traslado de material',
        'kilometraje_actual': 0,
        'placas': '600-226M',
        'numero_serie': '7V41U1626PH000915',
        'estado': 'activo',
    },
    {
        'equipo': 'Traila Fabricada',
        'nombre': 'traila',
        'tipo': 'traila',
        'marca': 'Fabricada',
        'modelo': 'Traila',
        'anio': None,
        'color': '',
        'uso_asignacion': 'Carga y traslado de material',
        'kilometraje_actual': 0,
        'placas': '',
        'numero_serie': '',
        'estado': 'activo',
    },
    {
        'equipo': 'Polaris Ranger 900',
        'nombre': 'El 900',
        'tipo': 'polaris',
        'marca': 'Polaris',
        'modelo': 'Ranger 900',
        'anio': 2019,
        'color': 'Rojo',
        'uso_asignacion': 'Trabajo en campo',
        'kilometraje_actual': 15697.0,
        'placas': '',
        'numero_serie': '16VAX1418K2013101',
        'estado': 'en_taller',
    },
    {
        'equipo': 'GMC Savana Van',
        'nombre': 'savana',
        'tipo': 'van',
        'marca': 'GMC',
        'modelo': 'Savana Van',
        'anio': 2009,
        'color': 'Azul',
        'uso_asignacion': 'Traslado de personal',
        'kilometraje_actual': 247911,
        'placas': 'EWV337D',
        'numero_serie': '1GJGG25KX91157082',
        'estado': 'activo',
    },
    {
        'equipo': 'Ford F250',
        'nombre': 'camioncito',
        'tipo': 'camion',
        'marca': 'Ford',
        'modelo': 'F250',
        'anio': 2008,
        'color': 'Blanco',
        'uso_asignacion': 'Trabajo en campo',
        'kilometraje_actual': 313619.2,
        'placas': 'EN0854D',
        'numero_serie': '1FTSX215X8EE40350',
        'estado': 'activo',
    },
]


def reemplazar_vehiculos(apps, schema_editor):
    Vehiculo = apps.get_model('flota', 'Vehiculo')
    Vehiculo.objects.filter(nombre__in=PLACEHOLDERS).delete()
    for datos in VEHICULOS_REALES:
        equipo = datos['equipo']
        Vehiculo.objects.get_or_create(equipo=equipo, defaults=datos)


def revertir_vehiculos(apps, schema_editor):
    Vehiculo = apps.get_model('flota', 'Vehiculo')
    equipos = [v['equipo'] for v in VEHICULOS_REALES]
    Vehiculo.objects.filter(equipo__in=equipos).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('flota', '0003_vehiculo_equipo_tipos_anio_opcional'),
    ]

    operations = [
        migrations.RunPython(reemplazar_vehiculos, revertir_vehiculos),
    ]
