# Generated by Django 6.0.6 on 2026-07-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0004_reemplazo_vehiculos_reales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='cables_corriente',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='caja_herramientas',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='carroceria_pintura',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='cruzeta',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='direccion_volante',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='filtro_aire',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='frenos_respuesta',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='gato',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='interiores_asientos',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='llanta_refaccion',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='luces_delanteras_traseras',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='neumaticos_presion',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='nivel_liquido_frenos',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='nivel_refrigerante',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='parabrisas_vidrios',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='suspension_amortiguadores',
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='anticongelante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='gasolina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='lavado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='neumatico_problema',
            field=models.CharField(blank=True, choices=[('ninguno', 'Sin problema'), ('delantero_izquierdo', 'Delantero izquierdo'), ('delantero_derecho', 'Delantero derecho'), ('trasero_izquierdo', 'Trasero izquierdo'), ('trasero_derecho', 'Trasero derecho')], max_length=25),
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='presion_llantas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='soplado_filtro_aire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fotochecklist',
            name='item',
            field=models.CharField(blank=True, choices=[('lavado', 'Lavado'), ('soplado_filtro_aire', 'Sopleteo de filtro de aire'), ('presion_llantas', 'Presión de llantas'), ('anticongelante', 'Anticongelante'), ('nivel_aceite', 'Nivel de aceite'), ('gasolina', 'Gasolina'), ('neumaticos', 'Neumáticos'), ('', 'General')], max_length=25),
        ),
    ]
