# Generated by Django 6.0.6 on 2026-07-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0005_checklist_items_con_foto_evidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='neumatico_problema',
        ),
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='nivel_aceite',
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='carga_traila',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='estado_fisico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='nivel_aceite_motor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='nivel_aceite_transmision',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checklistvehiculo',
            name='presion_llantas',
            field=models.CharField(blank=True, choices=[('bien', 'Presión correcta'), ('delantero_izquierdo', 'Delantera izquierda baja/ponchada'), ('delantero_derecho', 'Delantera derecha baja/ponchada'), ('trasero_izquierdo', 'Trasera izquierda baja/ponchada'), ('trasero_derecho', 'Trasera derecha baja/ponchada')], max_length=25),
        ),
        migrations.AlterField(
            model_name='fotochecklist',
            name='item',
            field=models.CharField(blank=True, choices=[('estado_fisico_derecho', 'Estado físico — costado derecho'), ('estado_fisico_izquierdo', 'Estado físico — costado izquierdo'), ('estado_fisico_frente', 'Estado físico — frente'), ('estado_fisico_trasero', 'Estado físico — trasero'), ('estado_fisico_interior', 'Estado físico — interior'), ('lavado', 'Lavado'), ('soplado_filtro_aire', 'Sopleteo de filtro de aire'), ('presion_llantas', 'Presión de llantas'), ('anticongelante', 'Anticongelante'), ('nivel_aceite_motor', 'Nivel de aceite motor'), ('nivel_aceite_transmision', 'Nivel de aceite transmisión'), ('gasolina', 'Gasolina'), ('carga_traila', 'Carga de la traila'), ('', 'General')], max_length=25),
        ),
    ]
