# Generated by Django 6.0.6 on 2026-07-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0006_checklist_estado_fisico_horas_traila'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistvehiculo',
            name='gasolina',
        ),
        migrations.AlterField(
            model_name='fotochecklist',
            name='item',
            field=models.CharField(blank=True, choices=[('kilometraje', 'Kilometraje / horómetro'), ('estado_fisico_derecho', 'Estado físico — costado derecho'), ('estado_fisico_izquierdo', 'Estado físico — costado izquierdo'), ('estado_fisico_frente', 'Estado físico — frente'), ('estado_fisico_trasero', 'Estado físico — trasero'), ('estado_fisico_interior', 'Estado físico — interior'), ('lavado', 'Lavado'), ('soplado_filtro_aire', 'Sopleteo de filtro de aire'), ('presion_llantas', 'Presión de llantas'), ('anticongelante', 'Anticongelante'), ('nivel_aceite_motor', 'Nivel de aceite motor'), ('nivel_aceite_transmision', 'Nivel de aceite transmisión'), ('carga_traila', 'Carga de la traila'), ('', 'General')], max_length=25),
        ),
    ]
