# Generated by Django 6.0.6 on 2026-07-12 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0007_checklist_kilometraje_gasolina_gauge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistvehiculo',
            name='llanta_cambiada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdvertenciaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertencias', to='flota.checklistvehiculo')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertencias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertencia de checklist',
                'verbose_name_plural': 'Advertencias de checklist',
                'ordering': ['-created_at'],
            },
        ),
    ]
