# Generated by Django 6.0.6 on 2026-07-12 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0008_llanta_cambiada_y_advertencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistvehiculo',
            name='traila',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'traila'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklists_traila', to='flota.vehiculo'),
        ),
    ]
