# Generated by Django 6.0.6 on 2026-07-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0009_checklist_traila_4x5'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistvehiculo',
            name='limpieza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='sin_carga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='sin_herramientas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fotochecklist',
            name='item',
            field=models.CharField(blank=True, choices=[('kilometraje', 'Kilometraje / horómetro'), ('estado_fisico_derecho', 'Estado físico — costado derecho'), ('estado_fisico_izquierdo', 'Estado físico — costado izquierdo'), ('estado_fisico_frente', 'Estado físico — frente'), ('estado_fisico_trasero', 'Estado físico — trasero'), ('estado_fisico_interior', 'Estado físico — interior'), ('lavado', 'Lavado'), ('soplado_filtro_aire', 'Sopleteo de filtro de aire'), ('presion_llantas', 'Presión de llantas'), ('anticongelante', 'Anticongelante'), ('nivel_aceite_motor', 'Nivel de aceite motor'), ('nivel_aceite_transmision', 'Nivel de aceite transmisión'), ('carga_traila', 'Carga de la traila'), ('limpieza', 'Limpieza'), ('sin_herramientas', 'Sin herramientas'), ('sin_carga', 'Sin carga'), ('', 'General')], max_length=25),
        ),
    ]
