# Generated by Django 6.0.6 on 2026-08-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0018_audiochecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistvehiculo',
            name='traila_limpieza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='traila_sin_carga',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistvehiculo',
            name='traila_sin_herramientas',
            field=models.BooleanField(default=False),
        ),
    ]
