# Generated by Django 6.0.6 on 2026-08-26 20:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0019_checklistvehiculo_traila_limpieza_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioAceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('realizado', 'Realizado'), ('pendiente', 'Pendiente'), ('en_reparacion', 'En reparación')], default='realizado', max_length=15)),
                ('km_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_aceite_registrados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_aceite', to='flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Cambio de aceite',
                'verbose_name_plural': 'Cambios de aceite',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
