# Generated by Django 6.0.6 on 2026-06-16 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('bloqueado', 'Bloqueado'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('motivo_bloqueo', models.CharField(blank=True, choices=[('falta_material', 'Falta de material'), ('falta_personal', 'Falta de personal'), ('falta_presupuesto', 'Falta de presupuesto'), ('incidente', 'Incidente'), ('clima', 'Clima'), ('otro', 'Otro')], max_length=20, null=True)),
                ('origen', models.CharField(choices=[('junta', 'Junta'), ('campo', 'Campo'), ('administracion', 'Administración'), ('sistema', 'Sistema')], default='junta', max_length=20)),
                ('modulo_relacionado', models.CharField(choices=[('hidraulica', 'Hidráulica'), ('flota', 'Flota'), ('inventario', 'Inventario'), ('proyectos', 'Proyectos'), ('personal', 'Personal'), ('ninguno', 'Ninguno')], default='ninguno', max_length=20)),
                ('registro_relacionado_id', models.IntegerField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ManyToManyField(blank=True, related_name='pendientes_asignados', to=settings.AUTH_USER_MODEL)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_pendientes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pendiente',
                'verbose_name_plural': 'Pendientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio', models.CharField(max_length=300)),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('nota', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pendiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pendientes.pendiente')),
            ],
            options={
                'verbose_name': 'Historial de pendiente',
                'verbose_name_plural': 'Historial de pendientes',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='FotoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='pendientes/%Y/%m/')),
                ('momento', models.CharField(choices=[('apertura', 'Apertura'), ('seguimiento', 'Seguimiento'), ('cierre', 'Cierre')], default='seguimiento', max_length=15)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pendiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='pendientes.pendiente')),
            ],
            options={
                'verbose_name': 'Foto de pendiente',
                'verbose_name_plural': 'Fotos de pendientes',
                'ordering': ['created_at'],
            },
        ),
    ]
