# Generated by Django 6.0.6 on 2026-06-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendiente',
            name='quien_compro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pendiente',
            name='se_compro_material',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendiente',
            name='solucion_cierre',
            field=models.TextField(blank=True, default=''),
        ),
    ]
