# Generated by Django 6.0.6 on 2026-06-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendientes', '0002_pendiente_quien_compro_pendiente_se_compro_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendiente',
            old_name='fecha_limite',
            new_name='fecha_asignacion',
        ),
        migrations.AlterField(
            model_name='pendiente',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('bloqueado', 'Bloqueado'), ('cerrado', 'Terminado')], default='abierto', max_length=20),
        ),
    ]
