# Generated by Django 6.0.6 on 2026-09-11 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_interno', models.CharField(blank=True, max_length=20, unique=True)),
                ('numero_factura', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=300)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='facturacion/%Y/%m/')),
                ('modulo_origen', models.CharField(choices=[('inventario', 'Inventario'), ('proyectos', 'Proyectos'), ('flota', 'Flota'), ('sanidad', 'Sanidad'), ('personal', 'Personal'), ('nomina', 'Nómina'), ('combustible', 'Combustible'), ('impuestos', 'Impuestos'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('referencia_descripcion', models.CharField(blank=True, max_length=200)),
                ('mes_reporte', models.CharField(blank=True, max_length=7)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_facturas', models.IntegerField()),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='facturacion/relaciones/%Y/%m/')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones_facturacion_generadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relación mensual',
                'verbose_name_plural': 'Relaciones mensuales',
                'ordering': ['-mes'],
            },
        ),
    ]
