# Generated by Django 6.0.6 on 2026-07-16 20:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(max_length=7)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de inventario',
                'verbose_name_plural': 'Categorías de inventario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('bodega', 'Bodega'), ('granero', 'Granero'), ('hangar', 'Hangar')], max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('unidad_medida', models.CharField(choices=[('pieza', 'Pieza'), ('saco', 'Saco'), ('rollo', 'Rollo'), ('litro', 'Litro'), ('metro', 'Metro'), ('caja', 'Caja'), ('kilogramo', 'Kilogramo'), ('par', 'Par'), ('juego', 'Juego'), ('otro', 'Otro')], default='pieza', max_length=15)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoriainventario')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.ubicacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_resultante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uso_descripcion', models.TextField(blank=True)),
                ('vehiculo_codigo', models.CharField(blank=True, max_length=20)),
                ('proyecto_referencia', models.CharField(blank=True, max_length=200)),
                ('fecha_movimiento', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('validado', models.BooleanField(default=False)),
                ('rechazado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='inventario/%Y/%m/')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_validados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-fecha_hora_registro'],
            },
        ),
    ]
