from django.db import migrations

CONEXIONES_HIDRAULICAS = 'Conexiones Hidráulicas'
ALIMENTOS_COSTALERA = 'Alimentos y Costalera'
CONSTRUCCION_MATERIALES = 'Construcción y Materiales'
COMBUSTIBLES = 'Combustibles'

BODEGA = 'bodega'
GRANERO = 'granero'
HANGAR = 'hangar'

PIEZA = 'pieza'
SACO = 'saco'
ROLLO = 'rollo'
LITRO = 'litro'
METRO = 'metro'

# (codigo, descripcion, categoria, ubicacion, unidad, stock_actual, stock_minimo)
PRODUCTOS = [
    # Conexiones hidráulicas — bodega
    ('SM-001', 'ABRAZADERA 1 3/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 97, 20),
    ('SM-002', 'ABRAZADERA 1', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 55, 10),
    ('SM-003', 'CODO 1"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 11, 5),
    ('SM-005', 'CODO GALV REFORZADO 1"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 3, 5),
    ('SM-006', 'COPLE GALV 1"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 25, 10),
    ('SM-007', 'COPLE GALV 2X4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 2, 0),
    ('SM-008', 'COPLE GALV 3/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 17, 5),
    ('SM-009', 'CODO 90 1 1/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 8, 0),
    ('SM-010', 'COPLE 1"1/4 CONICO', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 21, 0),
    ('SM-011', 'CODO 90 1" GALVANIZADO', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 49, 25),
    ('SM-012', 'COPLE ESPIGA 2"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 8, 0),
    ('SM-013', 'COPLE ESPIGA 3/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 22, 5),
    ('SM-014', 'LLAVE P/JARDIN 3/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 4, 0),
    ('SM-015', 'LLAVE DE PASO 1 1/2', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 1, 0),
    ('SM-016', 'LLAVE DE PASO 1 1/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 3, 0),
    ('SM-017', 'LLAVES DE PASO 1"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 1, 5),
    ('SM-018', 'NIPLE 1 1/2 X 6', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 6, 0),
    ('SM-019', 'NIPLE 1"1/2 X 2', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 7, 0),
    ('SM-020', 'NIPLES 1"1/2X3', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 1, 0),
    ('SM-021', 'NIPLES 1"1/2X6', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 6, 0),
    ('SM-022', 'NIPLES 1"1/4X4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 9, 0),
    ('SM-023', 'NIPLES 1"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 17, 5),
    ('SM-024', 'NIPLES 1"X4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 42, 0),
    ('SM-025', 'NIPLES 1X8', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 1, 0),
    ('SM-026', 'NIPLES 1X12', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 6, 0),
    ('SM-027', 'NIPLES DE 1X14', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 1, 0),
    ('SM-028', 'NIPLES 1X6', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 30, 0),
    ('SM-030', 'NIPLES 3/4 X 4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 4, 5),
    ('SM-031', 'NIPLES DE 4"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 9, 0),
    ('SM-032', 'PICO BOTELLA 2"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 3, 0),
    ('SM-033', 'PICO BOTELLA 1/2', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 13, 0),
    ('SM-034', 'PICO BOTELLA 3/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 15, 5),
    ('SM-035', 'PICO BOTELLA GALV 1"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 52, 10),
    ('SM-036', 'PURGADOR BRONCE 1"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 14, 10),
    ('SM-037', 'RED.CAMPANA 1" A 3/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 5, 5),
    ('SM-038', 'RED.CAMPANA 11/2 X 3/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 1, 0),
    ('SM-039', 'RED.CAMPANA 1"X1/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 8, 5),
    ('SM-040', 'RED.CAMPANA 1"X1/2', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 38, 10),
    ('SM-041', 'RED.CAMPANA 2X1', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 5, 0),
    ('SM-042', 'RED.CAMPANA 2X1"1/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 1, 0),
    ('SM-043', 'RED.CAMPANA 3/4 X 1/2', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 10, 5),
    ('SM-044', 'RED.CAMPANA 1 X 2', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 5, 2),
    ('SM-045', 'RED.CAMPANA 1/4X1', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 3, 0),
    ('SM-046', 'RED.MACHO A HEM. 3/4 X 1/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 10, 5),
    ('SM-047', 'TEE 1/2', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 1, 0),
    ('SM-048', 'TEE 1"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 32, 5),
    ('SM-050', 'TEE 3/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 12, 5),
    ('SM-051', 'TEE1"1/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 6, 0),
    ('SM-052', 'TUERCA UNION 1"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 25, 10),
    ('SM-053', 'TUERCA UNION 1/2"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 1, 0),
    ('SM-054', 'TUERCA UNION 2"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 28, 0),
    ('SM-055', 'TUERCA UNION 1"1/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 7, 0),
    ('SM-056', 'VALCULA CHECK 1"1/2', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 12, 5),
    ('SM-057', 'VALVULA FLOTADOR BRONCE 1"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 41, 5),
    ('SM-058', 'VALVULAS 1" BRONCE', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 23, 10),
    ('SM-059', 'VALVULA 1"1/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 5, 0),
    ('SM-060', 'VALVULA 1/2 BRONCE', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 1, 0),
    ('SM-061', 'VALVULA 2"1/2', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 2, 0),
    ('SM-062', 'VALVULA 3/4', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 9, 5),
    ('SM-063', 'VALVULA BEBEDERO 1"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 9, 5),
    ('SM-064', 'FLOTADOR BEBEDERO CON VARILLA', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 26, 0),
    ('SM-065', 'VALVULA CHECK 1"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 5, 5),
    ('SM-066', 'TUBOS DE PVC SANITARIO 4"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 10, 0),
    ('SM-067', 'COPLE PVC SANITARIO 4"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 28, 0),
    ('SM-068', 'CODO PVC SANITARIO 4"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 6, 0),
    ('SM-069', 'PEGAMENTO PVC AZUL 16 OZ', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 2, 0),
    ('SM-071', 'YEE 1 1/2', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 2, 0),
    ('SM-073', 'YEE 1"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 6, 2),
    ('SM-074', 'YEE 2"', CONEXIONES_HIDRAULICAS, BODEGA, PIEZA, 2, 0),
    ('SM-103', 'ROLLO DE MANGUERA 1"', CONEXIONES_HIDRAULICAS, BODEGA, ROLLO, 20, 1),
    ('SM-105', 'MANGUERA 3/4', CONEXIONES_HIDRAULICAS, BODEGA, METRO, 48, 0),

    # Alimentos y costalera — granero
    ('SM-076', 'ALPISTE', ALIMENTOS_COSTALERA, GRANERO, SACO, 1, 2),
    ('SM-077', 'OMOLIN TRADICIONAL', ALIMENTOS_COSTALERA, GRANERO, SACO, 9, 5),
    ('SM-078', 'PACAS', ALIMENTOS_COSTALERA, GRANERO, PIEZA, 162, 50),
    ('SM-079', 'PELE 3/4 GANADO', ALIMENTOS_COSTALERA, GRANERO, SACO, 12, 8),
    ('SM-080', 'SACO DE MAIZ', ALIMENTOS_COSTALERA, GRANERO, SACO, 136, 5),
    ('SM-081', 'SACO MILOMAIZ', ALIMENTOS_COSTALERA, GRANERO, SACO, 0, 5),
    ('SM-082', 'SACO MINERAL', ALIMENTOS_COSTALERA, GRANERO, SACO, 24, 10),
    ('SM-083', 'SACO DE SAL', ALIMENTOS_COSTALERA, GRANERO, SACO, 40, 20),
    ('SM-084', 'SALVADO', ALIMENTOS_COSTALERA, GRANERO, SACO, 2, 5),
    ('SM-194', 'SACO DE MAIZ MARRANOS', ALIMENTOS_COSTALERA, GRANERO, SACO, 0, 4),
    ('SM-195', 'SACO DE MAIZ GALLINAS', ALIMENTOS_COSTALERA, GRANERO, SACO, 0, 1),

    # Combustibles — hangar
    ('SM-130', 'GASOLINA', COMBUSTIBLES, HANGAR, LITRO, 600, 400),
    ('SM-131', 'DIESEL', COMBUSTIBLES, HANGAR, LITRO, 400, 400),

    # Construcción y materiales — bodega
    ('SM-086', 'ARMEX 15*15*4', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 12, 0),
    ('SM-088', 'BISAGRAS PARA PORTON', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 1, 0),
    ('SM-091', 'BOLSITAS DE GRAPAS', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 2, 0),
    ('SM-092', 'BOTES DE PINTURA BLANCA 19 LT', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 3, 0),
    ('SM-093', 'CAJA DE CLAVOS N5', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 1, 0),
    ('SM-094', 'CAJA DE GRAPAS', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 6, 0),
    ('SM-095', 'CANDADOS MASTER', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 3, 0),
    ('SM-097', 'CUBETA 19L ACEITE HIDRAULICO', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 1, 0),
    ('SM-098', 'DISCO DE CORTE 4 1/2', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 10, 0),
    ('SM-099', 'GALON THINNER', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 2, 0),
    ('SM-100', 'GRAPAS PARA CABLE', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 5, 0),
    ('SM-101', 'GRASA DE TUBO', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 7, 0),
    ('SM-102', 'HERRADURAS', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 8, 0),
    ('SM-104', 'ROLLO DE MAGUERA 2"', CONSTRUCCION_MATERIALES, BODEGA, ROLLO, 8, 0),
    ('SM-106', 'PANEL GANADERO', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 13, 0),
    ('SM-107', 'PEGAZULEJO ADHEX', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 26, 0),
    ('SM-108', 'PINTURA ROJO OXIDO', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 1, 0),
    ('SM-109', 'PLUVIOMETROS', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 19, 5),
    ('SM-110', 'PUERTAS 10FT', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 38, 0),
    ('SM-111', 'PUERTAS 4FT', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 5, 0),
    ('SM-113', 'ROLLO DE ALAMBRE GALVANIZADO', CONSTRUCCION_MATERIALES, BODEGA, ROLLO, 13, 0),
    ('SM-114', 'ROLLO DE ALAMBRE PUAS', CONSTRUCCION_MATERIALES, BODEGA, ROLLO, 29, 0),
    ('SM-115', 'ROLLO DE ALAMBRE RECOCIDO', CONSTRUCCION_MATERIALES, BODEGA, ROLLO, 16, 0),
    ('SM-116', 'ROLLO DE MALLA', CONSTRUCCION_MATERIALES, BODEGA, ROLLO, 1, 0),
    ('SM-117', 'SACO CAL', CONSTRUCCION_MATERIALES, BODEGA, SACO, 6, 0),
    ('SM-118', 'SACO DE CEMENTO 50 KG', CONSTRUCCION_MATERIALES, BODEGA, SACO, 17, 0),
    ('SM-119', 'SACO DE CEMENTO DE 25 KG', CONSTRUCCION_MATERIALES, BODEGA, SACO, 22, 0),
    ('SM-120', 'SERCHAS', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 465, 0),
    ('SM-122', 'TEFLONES', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 14, 0),
    ('SM-123', 'TUBO 2 7/8 16 FT', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 15.5, 0),
    ('SM-124', 'TUBO 2"3/8 12FT', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 42.5, 0),
    ('SM-125', 'TUBO 8FT', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 8, 0),
    ('SM-126', 'TUBOS DE 1" GALVANIZADOS', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 15, 10),
    ('SM-127', 'VARILLA 1/2', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 273, 0),
    ('SM-128', 'VARILLA 3/8*12', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 30, 0),
    ('SM-129', 'LLANTAS PARA SALEROS', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 60, 0),
    ('SM-158', 'CUBETA 19L ACEITE MOTOR DIESEL', CONSTRUCCION_MATERIALES, BODEGA, PIEZA, 0, 19),
]


def cargar(apps, schema_editor):
    CategoriaInventario = apps.get_model('inventario', 'CategoriaInventario')
    Ubicacion = apps.get_model('inventario', 'Ubicacion')
    Producto = apps.get_model('inventario', 'Producto')

    categorias = {c.nombre: c for c in CategoriaInventario.objects.all()}
    ubicaciones = {u.nombre: u for u in Ubicacion.objects.all()}

    for codigo, descripcion, categoria_nombre, ubicacion_nombre, unidad, stock, minimo in PRODUCTOS:
        Producto.objects.get_or_create(
            codigo=codigo,
            defaults={
                'descripcion': descripcion,
                'categoria': categorias[categoria_nombre],
                'ubicacion': ubicaciones[ubicacion_nombre],
                'unidad_medida': unidad,
                'stock_actual': stock,
                'stock_minimo': minimo,
            },
        )


def revertir(apps, schema_editor):
    Producto = apps.get_model('inventario', 'Producto')
    Producto.objects.filter(codigo__in=[p[0] for p in PRODUCTOS]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('inventario', '0002_precarga_categorias_ubicaciones'),
    ]

    operations = [
        migrations.RunPython(cargar, revertir),
    ]
