# Generated by Django 6.0.6 on 2026-07-21 21:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_precarga_productos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_envio', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_envio', models.TimeField(blank=True, null=True)),
                ('vehiculo', models.CharField(blank=True, max_length=100)),
                ('notas_envio', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('en_transito', 'En tránsito'), ('entregado', 'Entregado'), ('entregado_parcial', 'Entregado parcial')], default='en_transito', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envío de material',
                'verbose_name_plural': 'Envíos de material',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FotoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='inventario/envios/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('momento', models.CharField(choices=[('salida', 'Salida'), ('llegada', 'Llegada')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventario.enviomaterial')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de envío',
                'verbose_name_plural': 'Fotos de envío',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_libre', models.CharField(blank=True, max_length=200)),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_enviada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidad', models.CharField(blank=True, max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('es_producto_nuevo', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_solicitados', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Ítem de solicitud',
                'verbose_name_plural': 'Ítems de solicitud',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_recepcion', models.TimeField(blank=True, null=True)),
                ('estado_general', models.CharField(choices=[('completo', 'Completo'), ('parcial', 'Parcial'), ('con_danios', 'Con daños')], max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='inventario.enviomaterial')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepción de material',
                'verbose_name_plural': 'Recepciones de material',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_item', models.CharField(choices=[('ok', 'OK'), ('daniado', 'Dañado'), ('faltante', 'Faltante')], max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='inventario/recepciones/%Y/%m/')),
                ('item_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='inventario.itemsolicitud')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.recepcionmaterial')),
            ],
            options={
                'verbose_name': 'Ítem de recepción',
                'verbose_name_plural': 'Ítems de recepción',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReporteFaltanteDanio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('faltante', 'Faltante'), ('danio', 'Daño'), ('irregularidad', 'Irregularidad')], max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='inventario/reportes/%Y/%m/')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_seguimiento', 'En seguimiento'), ('resuelto', 'Resuelto')], default='abierto', max_length=15)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('notas_resolucion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_faltante_danio', to='inventario.producto')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_faltante_danio', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_resueltos', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ubicacion')),
            ],
            options={
                'verbose_name': 'Reporte de faltante o daño',
                'verbose_name_plural': 'Reportes de faltantes y daños',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('area', models.CharField(choices=[('campo', 'Campo'), ('hidraulica', 'Hidráulica'), ('construccion', 'Construcción'), ('ganado', 'Ganado'), ('flota', 'Flota'), ('administracion', 'Administración'), ('otro', 'Otro')], max_length=20)),
                ('descripcion_necesidad', models.TextField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada'), ('en_compra', 'En compra'), ('enviada_rancho', 'Enviada al rancho'), ('recibida_parcial', 'Recibida parcial'), ('recibida_completa', 'Recibida completa')], default='borrador', max_length=20)),
                ('autorizado_en', models.DateTimeField(blank=True, null=True)),
                ('notas_autorizacion', models.TextField(blank=True)),
                ('fecha_requerida', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de material',
                'verbose_name_plural': 'Solicitudes de material',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='itemsolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.solicitudmaterial'),
        ),
        migrations.AddField(
            model_name='enviomaterial',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='inventario.solicitudmaterial'),
        ),
    ]
