# Generated by Django 6.0.6 on 2026-08-07 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0019_checklistvehiculo_traila_limpieza_and_more'),
        ('inventario', '0004_enviomaterial_fotoenvio_itemsolicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_combustible', to='flota.vehiculo'),
        ),
    ]
