# Generated by Django 6.0.6 on 2026-08-10 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_movimientoinventario_vehiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_factura', models.ImageField(upload_to='inventario/compras/%Y/%m/')),
                ('notas', models.TextField(blank=True)),
                ('fecha_compra', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comprado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_realizadas', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_registradas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='inventario.solicitudmaterial')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelacionCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada')], default='borrador', max_length=10)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compras', models.ManyToManyField(blank=True, related_name='relaciones', to='inventario.compra')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones_compras_generadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relación de compras',
                'verbose_name_plural': 'Relaciones de compras',
                'ordering': ['-created_at'],
            },
        ),
    ]
