# Generated by Django 6.0.6 on 2026-08-10 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_compra_relacioncompras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='movimiento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='inventario.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='solicitud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compra', to='inventario.solicitudmaterial'),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movimiento__isnull', True), ('solicitud__isnull', False)), models.Q(('movimiento__isnull', False), ('solicitud__isnull', True)), _connector='OR'), name='compra_de_solicitud_xor_movimiento'),
        ),
    ]
