# Generated by Django 6.0.6 on 2026-08-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_compra_movimiento_compra_proveedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudmaterial',
            name='fecha_requerida',
        ),
    ]
