# Generated by Django 6.0.6 on 2026-08-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_remove_solicitudmaterial_fecha_requerida'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionmaterial',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='inventario/recepciones/audios/%Y/%m/'),
        ),
    ]
