# Generated by Django 6.0.6 on 2026-08-24 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_recepcionmaterial_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_entrada', to='inventario.solicitudmaterial'),
        ),
        migrations.AddField(
            model_name='recepcionmaterial',
            name='entrada_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recepcionmaterial',
            name='entrada_confirmada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepcionmaterial',
            name='entrada_confirmada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
