# Generated by Django 6.0.6 on 2026-09-24 17:43

from django.db import migrations, models

# 'bodega', 'granero' y 'hangar' ya existían (ver 0002_precarga_categorias_ubicaciones) y se
# conservan porque productos reales ya las referencian. El resto es el catálogo completo de
# ubicaciones de INVENTARIO que mandó Alfredo (2026-09-24).
NUEVAS_UBICACIONES = [
    {'nombre': 'alacena', 'descripcion': 'Alimento personal'},
    {'nombre': 'almacen', 'descripcion': ''},
    {'nombre': 'bodega_nueva', 'descripcion': ''},
    {'nombre': 'oficina_ca', 'descripcion': ''},
    {'nombre': 'oficina_reserva', 'descripcion': ''},
    {'nombre': 'taller', 'descripcion': ''},
    {'nombre': 'patio_yarda', 'descripcion': ''},
]


def cargar(apps, schema_editor):
    Ubicacion = apps.get_model('inventario', 'Ubicacion')
    for datos in NUEVAS_UBICACIONES:
        Ubicacion.objects.get_or_create(nombre=datos['nombre'], defaults=datos)


def revertir(apps, schema_editor):
    Ubicacion = apps.get_model('inventario', 'Ubicacion')
    Ubicacion.objects.filter(nombre__in=[u['nombre'] for u in NUEVAS_UBICACIONES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_producto_clase_abc_producto_clasificado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(choices=[('alacena', 'Alacena'), ('almacen', 'Almacén'), ('bodega', 'Bodega'), ('bodega_nueva', 'Bodega Nueva'), ('granero', 'Granero'), ('hangar', 'Hangar'), ('oficina_ca', 'Oficina CA'), ('oficina_reserva', 'Oficina Reserva'), ('taller', 'Taller'), ('patio_yarda', 'Patio/Yarda')], max_length=20, unique=True),
        ),
        migrations.RunPython(cargar, revertir),
    ]
