# Generated by Django 6.0.6 on 2026-10-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_ubicacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcionmaterial',
            name='en_yarda',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
