# Generated by Django 6.0.6 on 2026-06-15 02:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHidraulico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_medicion', models.CharField(choices=[('pila_norte_1', 'Pila Norte 1'), ('pila_norte_2', 'Pila Norte 2'), ('pila_sur_1', 'Pila Sur 1'), ('pila_centro', 'Pila Centro'), ('fluxometro_linea_a', 'Fluxómetro Línea A'), ('fluxometro_linea_b', 'Fluxómetro Línea B'), ('manometro_trampa_sur', 'Manómetro Trampa Sur'), ('manometro_casa_norte', 'Manómetro Casa Norte'), ('pluviometro_1', 'Pluviómetro 1'), ('pluviometro_2', 'Pluviómetro 2')], max_length=30)),
                ('estado', models.CharField(choices=[('normal', 'Normal'), ('alerta', 'Alerta'), ('falla', 'Falla')], max_length=10)),
                ('nivel_pulgadas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('caudal_m3h', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('presion_psi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lluvia_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='hidraulica/%Y/%m/')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('validado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_hidraulicos', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_hidraulicos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro hidráulico',
                'verbose_name_plural': 'Registros hidráulicos',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
