# Generated by Django 6.0.6 on 2026-06-15 21:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidraulica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Generador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('chapote', 'Chapote'), ('rancho', 'Rancho'), ('margaritas', 'Margaritas')], max_length=20, unique=True)),
                ('marca_modelo', models.CharField(max_length=100)),
                ('horas_operacion', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generadores_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generador',
                'verbose_name_plural': 'Generadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistGenerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('nivel_aceite', models.BooleanField(default=False)),
                ('nivel_refrigerante', models.BooleanField(default=False)),
                ('filtro_aire', models.BooleanField(default=False)),
                ('sin_fugas', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_generador', to=settings.AUTH_USER_MODEL)),
                ('generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='hidraulica.generador')),
            ],
            options={
                'verbose_name': 'Checklist de generador',
                'verbose_name_plural': 'Checklists de generadores',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='AlertaMantenimientoGenerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=255)),
                ('horas_intervalo', models.IntegerField(blank=True, null=True)),
                ('meses_intervalo', models.IntegerField(blank=True, null=True)),
                ('ultima_alerta', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_mantenimiento', to='hidraulica.generador')),
            ],
            options={
                'verbose_name': 'Alerta de mantenimiento de generador',
                'verbose_name_plural': 'Alertas de mantenimiento de generadores',
                'ordering': ['generador', 'horas_intervalo'],
            },
        ),
    ]
