# Generated by Django 6.0.6 on 2026-07-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hidraulica', '0003_generadores_iniciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cazuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('noria', models.CharField(choices=[('rosita', 'Rosita'), ('margaritas', 'Margaritas'), ('chapote', 'Chapote')], max_length=20)),
                ('lat', models.DecimalField(decimal_places=12, max_digits=18)),
                ('lng', models.DecimalField(decimal_places=12, max_digits=18)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cazuela',
                'verbose_name_plural': 'Cazuelas',
                'ordering': ['noria', 'nombre'],
            },
        ),
    ]
